## 模型pipeline

In [51]:
# 导入相关包
import warnings
warnings.filterwarnings('ignore')
import pandas as pd
import matplotlib.pyplot as plt

pd.set_option('display.max_rows', 100)
pd.set_option('display.max_columns', 100)

In [52]:
dataset = pd.read_csv("data.csv", encoding="gbk")
dataset.head()

,Unnamed: 0,custid,trade_no,bank_card_no,low_volume_percent,middle_volume_percent,take_amount_in_later_12_month_highest,trans_amount_increase_rate_lately,trans_activity_month,trans_activity_day,transd_mcc,trans_days_interval_filter,trans_days_interval,regional_mobility,student_feature,repayment_capability,is_high_user,number_of_trans_from_2011,first_transaction_time,historical_trans_amount,historical_trans_day,rank_trad_1_month,trans_amount_3_month,avg_consume_less_12_valid_month,abs,top_trans_count_last_1_month,avg_price_last_12_month,avg_price_top_last_12_valid_month,reg_preference_for_trad,trans_top_time_last_1_month,trans_top_time_last_6_month,consume_top_time_last_1_month,consume_top_time_last_6_month,cross_consume_count_last_1_month,trans_fail_top_count_enum_last_1_month,trans_fail_top_count_enum_last_6_month,trans_fail_top_count_enum_last_12_month,consume_mini_time_last_1_month,max_cumulative_consume_later_1_month,max_consume_count_later_6_month,railway_consume_count_last_12_month,pawns_auctions_trusts_consume_last_1_month,pawns_auctions_trusts_consume_last_6_month,jewelry_consume_count_last_6_month,status,source,first_transaction_day,trans_day_last_12_month,id_name,apply_score,apply_credibility,query_org_count,query_finance_count,query_cash_count,query_sum_count,latest_query_time,latest_one_month_apply,latest_three_month_apply,latest_six_month_apply,loans_score,loans_credibility_behavior,loans_count,loans_settle_count,loans_overdue_count,loans_org_count_behavior,consfin_org_count_behavior,loans_cash_count,latest_one_month_loan,latest_three_month_loan,latest_six_month_loan,history_suc_fee,history_fail_fee,latest_one_month_suc,latest_one_month_fail,loans_long_time,loans_latest_time,loans_credit_limit,loans_credibility_limit,loans_org_count_current,loans_product_count,loans_max_limit,loans_avg_limit,consfin_credit_limit,consfin_credibility,consfin_org_count_current,consfin_product_count,consfin_max_limit,consfin_avg_limit,latest_query_day,loans_latest_day
0,5,2791858,20180507115231274000000023057383,卡号1,0.01,0.99,0,0.90,0.55,0.313,17.0,27.0,26.0,3.0,NaN,19890,0,30.0,20130817.0,149050,151.0,0.40,34030,7.0,3920,0.15,1020,0.55,一线城市,4.0,19.0,4.0,19.0,1.0,1.0,2.0,2.0,5.0,2170,6.0,0.0,1970,18040,0.0,1,xs,1738.0,85.0,蒋红,583.0,79.0,8.0,2.0,6.0,10.0,2018-04-25,2.0,5.0,8.0,552.0,73.0,37.0,34.0,2.0,10.0,1.0,9.0,1.0,1.0,13.0,37.0,7.0,1.0,0.0,341.0,2018-04-19,2200.0,72.0,9.0,10.0,2900.0,1688.0,1200.0,75.0,1.0,2.0,1200.0,1200.0,12.0,18.0
1,10,534047,20180507121002192000000023073000,卡号1,0.02,0.94,2000,1.28,1.00,0.458,19.0,30.0,14.0,4.0,1.0,16970,0,23.0,20160402.0,302910,224.0,0.35,10590,5.0,6950,0.05,1210,0.50,一线城市,13.0,30.0,13.0,30.0,0.0,0.0,3.0,3.0,330.0,2100,9.0,0.0,1820,15680,0.0,0,xs,779.0,84.0,崔向朝,653.0,73.0,7.0,4.0,2.0,8.0,2018-05-03,2.0,6.0,8.0,635.0,76.0,37.0,36.0,0.0,17.0,5.0,12.0,2.0,2.0,8.0,49.0,4.0,2.0,1.0,353.0,2018-05-05,2000.0,74.0,12.0,12.0,3500.0,1758.0,15100.0,80.0,5.0,6.0,22800.0,9360.0,4.0,2.0
2,12,2849787,20180507125159718000000023114911,卡号1,0.04,0.96,0,1.00,1.00,0.114,13.0,68.0,22.0,1.0,NaN,9710,0,9.0,20170617.0,11520,31.0,1.00,5710,5.0,840,0.65,570,0.65,一线城市,0.0,68.0,0.0,68.0,0.0,3.0,6.0,6.0,0.0,0,3.0,0.0,0,0,0.0,1,xs,338.0,95.0,王中云,654.0,76.0,11.0,5.0,5.0,16.0,2018-05-05,5.0,5.0,14.0,633.0,83.0,4.0,2.0,0.0,3.0,1.0,2.0,2.0,2.0,4.0,2.0,2.0,1.0,1.0,157.0,2018-05-01,1500.0,77.0,2.0,2.0,1600.0,1250.0,4200.0,87.0,1.0,1.0,4200.0,4200.0,2.0,6.0
3,13,1809708,20180507121358683000000388283484,卡号1,0.00,0.96,2000,0.13,0.57,0.777,22.0,14.0,6.0,3.0,NaN,6210,0,33.0,20130516.0,491130,360.0,0.15,91690,7.0,46850,0.05,1290,0.45,三线城市,6.0,8.0,6.0,8.0,0.0,1.0,8.0,8.0,31700.0,8140,9.0,0.0,2700,27970,0.0,0,xs,1831.0,82.0,何洋洋,595.0,79.0,12.0,7.0,4.0,22.0,2018-05-05,3.0,16.0,17.0,542.0,75.0,85.0,81.0,4.0,22.0,5.0,17.0,2.0,4.0,34.0,91.0,26.0,2.0,0.0,355.0,2018-05-03,1800.0,74.0,17.0,18.0,3200.0,1541.0,16300.0,80.0,5.0,5.0,30000.0,12180.0,2.0,4.0
4,14,2499829,20180507115448545000000388205844,卡号1,0.01,0.99,0,0.46,1.00,0.175,13.0,66.0,42.0,1.0,NaN,11150,0,12.0,20170312.0,61470,63.0,0.65,9770,6.0,760,1.00,1110,0.50,一线城市,0.0,66.0,0.0,66.0,0.0,3.0,3.0,3.0,0.0,1000,3.0,0.0,0,6410,0.0,1,xs,435.0,88.0,赵洋,541.0,75.0,11.0,3.0,4.0,14.0,2018-04-15,6.0,8.0,9.0,479.0,73.0,37.0,32.0,6.0,12.0,2.0,10.0,0.0,0.0,10.0,36.0,25.0,0.0,0.0,360.0,2018-01-07,1800.0,72.0,10.0,10.0,2300.0,1630.0,8300.0,79.0,2.0,2.0,8400.0,8250.0,22.0,120.0

In [53]:
# 去除一些没用的列
dataset.drop(["Unnamed: 0", "custid", "trade_no", "bank_card_no", "source", "id_name"], axis=1, inplace=True)
dataset.head().T

,0,1,2,3,4
low_volume_percent,0.01,0.02,0.04,0,0.01
middle_volume_percent,0.99,0.94,0.96,0.96,0.99
take_amount_in_later_12_month_highest,0,2000,0,2000,0
trans_amount_increase_rate_lately,0.9,1.28,1,0.13,0.46
trans_activity_month,0.55,1,1,0.57,1
trans_activity_day,0.313,0.458,0.114,0.777,0.175
transd_mcc,17,19,13,22,13
trans_days_interval_filter,27,30,68,14,66
trans_days_interval,26,14,22,6,42
regional_mobility,3,4,1,3,1
student_feature,NaN,1,NaN,NaN,NaN
repayment_capability,19890,16970,9710,6210,11150
is_high_user,0,0,0,0,0
number_of_trans_from_2011,30,23,9,33,12
first_transaction_time,2.01308e+07,2.01604e+07,2.01706e+07,2.01305e+07,2.01703e+07
historical_trans_amount,149050,302910,11520,491130,61470
historical_trans_day,151,224,31,360,63
rank_trad_1_month,0.4,0.35,1,0.15,0.65
trans_amount_3_month,34030,10590,5710,91690,9770
avg_consume_less_12_valid_month,7,5,5,7,6
abs,3920,6950,840,46850,760
top_trans_count_last_1_month,0.15,0.05,0.65,0.05,1
avg_price_last_12_month,1020,1210,570,1290,1110
avg_price_top_last_12_valid_month,0.55,0.5,0.65,0.45,0.5
reg_preference_for_trad,一线城市,一线城市,一线城市,三线城市,一线城市
trans_top_time_last_1_month,4,13,0,6,0
trans_top_time_last_6_month,19,30,68,8,66
consume_top_time_last_1_month,4,13,0,6,0
consume_top_time_last_6_month,19,30,68,8,66
cross_consume_count_last_1_month,1,0,0,0,0
trans_fail_top_count_enum_last_1_month,1,0,3,1,3
trans_fail_top_count_enum_last_6_month,2,3,6,8,3
trans_fail_top_count_enum_last_12_month,2,3,6,8,3
consume_mini_time_last_1_month,5,330,0,31700,0
max_cumulative_consume_later_1_month,2170,2100,0,8140,1000
max_consume_count_later_6_month,6,9,3,9,3
railway_consume_count_last_12_month,0,0,0,0,0
pawns_auctions_trusts_consume_last_1_month,1970,1820,0,2700,0
pawns_auctions_trusts_consume_last_6_month,18040,15680,0,27970,6410
jewelry_consume_count_last_6_month,0,0,0,0,0
status,1,0,1,0,1
first_transaction_day,1738,779,338,1831,435
trans_day_last_12_month,85,84,95,82,88
apply_score,583,653,654,595,541
apply_credibility,79,73,76,79,75
query_org_count,8,7,11,12,11
query_finance_count,2,4,5,7,3
query_cash_count,6,2,5,4,4
query_sum_count,10,8,16,22,14
latest_query_time,2018-04-25,2018-05-03,2018-05-05,2018-05-05,2018-04-15
latest_one_month_apply,2,2,5,3,6
latest_three_month_apply,5,6,5,16,8
latest_six_month_apply,8,8,14,17,9
loans_score,552,635,633,542,479
loans_credibility_behavior,73,76,83,75,73
loans_count,37,37,4,85,37
loans_settle_count,34,36,2,81,32
loans_overdue_count,2,0,0,4,6
loans_org_count_behavior,10,17,3,22,12
consfin_org_count_behavior,1,5,1,5,2
loans_cash_count,9,12,2,17,10
latest_one_month_loan,1,2,2,2,0
latest_three_month_loan,1,2,2,4,0
latest_six_month_loan,13,8,4,34,10
history_suc_fee,37,49,2,91,36
history_fail_fee,7,4,2,26,25
latest_one_month_suc,1,2,1,2,0
latest_one_month_fail,0,1,1,0,0
loans_long_time,341,353,157,355,360
loans_latest_time,2018-04-19,2018-05-05,2018-05-01,2018-05-03,2018-01-07
loans_credit_limit,2200,2000,1500,1800,1800
loans_credibility_limit,72,74,77,74,72
loans_org_count_current,9,12,2,17,10
loans_product_count,10,12,2,18,10
loans_max_limit,2900,3500,1600,3200,2300
loans_avg_limit,1688,1758,1250,1541,1630
consfin_credit_limit,1200,15100,4200,16300,8300
consfin_credibility,75,80,87,80,79
consfin_org_count_current,1,5,1,5,2
consfin_product_count,2,6,1,5,2
consfin_max_limit,1200,22800,4200,30000,8400
consfin_avg_limit,1200,9360,4200,12180,8250
latest_query_day,12,4,2,2,22
loans_latest_day,18,2,6,4,120

## TODO 特征工程
### 现我们先直接选择一些特征先， 在此之前先生成训练集和测试集

In [54]:
# 创建测试集 ，为了防止采样偏差，这里使用分层采样
# 测试集通常被忽略，但实际是机器学习非常重要的一部分。
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.model_selection import StratifiedShuffleSplit

split = StratifiedShuffleSplit(n_splits=1, test_size=0.3, random_state=2018)
for train_index, test_index in split.split(dataset, dataset["status"]):
    strat_train_set=dataset.loc[train_index]
    strat_test_set=dataset.loc[test_index]

# 分层采样就是按照这里给的 status 分类比例来的
dataset["status"].value_counts()/len(dataset)

0    0.749053
1    0.250947
Name: status, dtype: float64

In [55]:
# 特征工程
# ？？？ todo

In [56]:
train = strat_train_set.copy()
corr_matrix = train.corr()
selected_columns = list(corr_matrix['status'].sort_values(ascending = False)[:10].index.values)
X_train= train[selected_columns].drop(["status"], axis=1)
y_train= train[["status"]]

In [57]:
X_train.head()

,trans_fail_top_count_enum_last_1_month,history_fail_fee,loans_overdue_count,latest_one_month_fail,rank_trad_1_month,top_trans_count_last_1_month,trans_fail_top_count_enum_last_6_month,trans_fail_top_count_enum_last_12_month,trans_day_last_12_month
1831,2.0,3.0,0.0,0.0,1.00,1.00,2.0,2.0,93.0
1979,2.0,NaN,NaN,NaN,0.30,0.05,10.0,10.0,82.0
4101,4.0,14.0,2.0,0.0,0.55,0.30,4.0,4.0,94.0
4133,4.0,36.0,4.0,1.0,0.25,0.05,6.0,6.0,84.0
3388,4.0,9.0,2.0,0.0,0.45,0.40,6.0,6.0,85.0

In [58]:
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder


def transform(df):
    """ 
        特征转换
    """
    # 类别属性
    # cat_columns = ['reg_preference_for_trad', 'latest_query_time', 'loans_latest_time']
    cat_columns = []
    # 数值属性
    num_cols = X_train.columns
    steps = [
        ('imputer', SimpleImputer(strategy="median")),
        ('ss', StandardScaler())]
    num_pipe = Pipeline(steps)
    transformers = [
        ('num', num_pipe, num_cols),
        ("cat", OneHotEncoder(), cat_columns),
    ]
    ct = ColumnTransformer(transformers=transformers)
    X_num_transformed = ct.fit_transform(df)
    return X_num_transformed

X = transform(X_train)
X

array([[ 0.19654138, -0.57415649, -0.71107072, ..., -0.54756914,
        -0.6495506 ,  0.18756317],
       [ 0.19654138, -0.32710286, -0.38690899, ...,  1.18003876,
         0.94738629, -0.3731041 ],
       [ 1.26937678, -0.12122484, -0.06274727, ..., -0.11566717,
        -0.25031638,  0.23853292],
       ...,
       [-0.33987632,  1.2787457 ,  0.58557619, ...,  0.96408777,
         0.74776918, -0.16922509],
       [-0.87629402, -0.65650769, -0.71107072, ..., -0.33161815,
        -0.44993349, -0.01631584],
       [-0.33987632, -0.32710286,  0.90973792, ..., -0.33161815,
        -0.44993349, -0.22019484]])

In [59]:
from sklearn.model_selection import StratifiedKFold
from sklearn.model_selection import cross_val_score

from sklearn.linear_model import Ridge
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
from sklearn.naive_bayes import GaussianNB
from sklearn.svm import SVC
from sklearn.ensemble import AdaBoostClassifier
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import ExtraTreesClassifier

models = [
    ('LR'   , LogisticRegression()),
    ('LDA'  , LinearDiscriminantAnalysis()),
    ('KNN'  , KNeighborsClassifier()),
    ('CART' , DecisionTreeClassifier()),
    ('NB'   , GaussianNB()),
    ('SVM'  , SVC(probability=True)),
    ('AB'   , AdaBoostClassifier()),
    ('GBM'  , GradientBoostingClassifier()),
    ('RF'   , RandomForestClassifier()),
    ('ET'   , ExtraTreesClassifier())
]

def run_models(x, y, models):
    num_folds = 10
    scoring = 'accuracy'

    results = []
    names = []
    for name, model in models:
        kfold = StratifiedKFold(n_splits=num_folds, random_state=123)
        cv_results = cross_val_score(model, x, y, cv=kfold, scoring=scoring)
        results.append(cv_results)
        names.append(name)
        msg = "%s: %f (%f)" % (name, cv_results.mean(), cv_results.std())
        print(msg)
        
    return names, results

In [60]:
# 运行模型
names, results = run_models(X, y_train, models)

LR: 0.786910 (0.014265)
LDA: 0.786313 (0.013613)
KNN: 0.761350 (0.009498)
CART: 0.688624 (0.024439)
NB: 0.767360 (0.018073)
SVM: 0.782998 (0.014239)
AB: 0.787797 (0.012973)
GBM: 0.785414 (0.014027)
RF: 0.763161 (0.015031)
ET: 0.758342 (0.012885)